Move fallback logic into main entry script
1. rename native binary to 'mvnd-native-<os>-<arch>'
2. add environment switch MVND_ENTRY_FALLBACK, default 'true' enables
   the fallback logic, set to 'false' to force execute the native mvnd.
3. rename mvnd.sh to mvnd

diff --git a/dist/src/main/distro/bin/mvnd b/dist/src/main/distro/bin/mvnd
--- a/dist/src/main/distro/bin/mvnd
+++ b/dist/src/main/distro/bin/mvnd
@@ -25,6 +25,9 @@
 #   JAVA_HOME       Must point at your Java Development Kit installation.
 #   MAVEN_OPTS      (Optional) Java runtime options used when Maven is executed.
 #   MAVEN_SKIP_RC   (Optional) Flag to disable loading of mavenrc files.
+#   MVND_ENTRY_FALLBACK (Optional) Flag to disable fallback to pure java mvnd,
+#                       default 'true' enable the fallback,
+#                       set to 'false' to force execute the native mvnd.
 # -----------------------------------------------------------------------------
 
 if [ -z "$MAVEN_SKIP_RC" ] ; then
@@ -88,6 +91,38 @@ if $mingw ; then
     JAVA_HOME=`(cd "$JAVA_HOME"; pwd)`
   # TODO classpath?
 fi
+
+# force execute native image
+if [ "${MVND_ENTRY_FALLBACK:-true}" = false ]; then
+  MVND_CMD=$(echo "$MVND_HOME"/bin/mvnd-native-*)
+  [ ! -x "$MVND_CMD" ] || exec "$MVND_CMD" "$@"
+  echo "Cannot run native mvnd '${MVND_CMD-}'!" >&2
+  exit 1
+fi
+
+case "$(uname -a)" in
+(CYGWIN*|MINGW*) os=windows arch=$(uname -m) ;;
+(Darwin*x86_64) os=darwin arch=amd64 ;;
+(Darwin*arm64) os=darwin arch=aarch64 ;;
+(Linux*) os=linux arch=$(uname -m) ;;
+(*) os=$(uname) arch=$(uname -m) ;;
+esac
+[ "${arch-}" != x86_64 ] || arch=amd64
+[ "${arch-}" != arm64 ] || arch=aarch64
+
+# try native image
+MVND_CMD="$MVND_HOME/bin/mvnd-native-$os-$arch"
+if [ -x "$MVND_CMD" ]; then
+  is_native=true
+  if [ "$os" = linux ]; then
+    case "$(ldd "$MVND_CMD")" in
+    (''|*"not found"*) is_native=false ;;
+    esac
+  fi
+  ! $is_native || exec "$MVND_CMD" "$@"
+fi
+
+# fallback to pure java version
 
 if [ -z "$JAVA_HOME" ] ; then
   JAVACMD="`\\unset -f command; \\command -v java`"
